install:
  # Initialize all submodules
  - git submodule update --init --recursive

  # move up out of Gunship directory
  - cd ..

  # upgrade cmake
  - choco install cmake

  # download SDL2 SDK
  - appveyor DownloadFile http://libsdl.org/release/SDL2-devel-2.0.3-VC.zip
  - 7z x SDL2-devel-2.0.3-VC.zip -oC:\

  # download Ogre2.0 SDK
  - appveyor DownloadFile https://www.dropbox.com/s/789wnaiysq9kkiu/OgreSDK_v2-0-0.zip?dl=1
  - 7z x OgreSDK_v2-0-0.zip -oC:\

  # configure Gunship solution
  - mkdir build
  - cd build
  - cmake ../Gunship -DCMAKE_BUILD_TYPE=Release -DOGRE_HOME:PATH=C:\OgreSDK_2-0-0

environment:
  SDL2: C:\SDL2-2.0.3

build:
  project: C:\projects\build\Gunship.sln

test_script:
  - cd tests
  - GunshipTests
