install:
  - dir
  - cd ..
  - dir

  # download SDL2 SDK
  - appveyor DownloadFile http://libsdl.org/release/SDL2-devel-2.0.3-VC.zip
  - 7z SDL2-devel-2.0.3-VC.zip -oC:\
  - dir
  
build_script:
  - mkdir build
  - cd build
  - cmake ../Gunship
  - dir
  
environment:
  SDL2: C:\SDL2-2.0.3
