install:
  - dir
  - cd ..
  - dir

  # download SDL2 SDK
  - appveyor DownloadFile http://libsdl.org/release/SDL2-devel-2.0.3-VC.zip
  - dir
  
build:
  - mkdir build
  - cd build
  - cmake ../Gunship
  - dir
  
