install:
  - cd ..

  # download SDL2 SDK
  - appveyor DownloadFile http://libsdl.org/release/SDL2-devel-2.0.3-VC.zip
  - dir
  - 7z x SDL2-devel-2.0.3-VC.zip -oC:\
  
build_script:
  - mkdir build
  - cd build
  - cmake ../Gunship
  
environment:
  SDL2: C:\SDL2-2.0.3
